spring:
  datasource:
    url: jdbc:postgresql://localhost:6000/jwt_security
    username: postgres
    password: jojo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
